# Generated by Django 3.1.1 on 2020-10-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('imovel', '0002_auto_20201003_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='regiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propriedade_regiao', to='localizacao.regiao', verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propriedade_tipo', to='imovel.tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
