# Generated by Django 3.1.1 on 2020-10-04 19:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0003_auto_20201004_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='posicao',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Posição'),
        ),
    ]
