# Generated by Django 3.1.1 on 2020-10-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0004_propriedade_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
