# Generated by Django 3.1.1 on 2020-10-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade', to='localizacao.regiao', verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['id', 'nome'],
            },
        ),
    ]
