# Generated by Django 3.1.1 on 2020-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0002_auto_20201004_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='regiao',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
